### PR TITLE
Fixing recipes from hardcoded Create Brass to Forge Brass Ingot Tag

### PR DESCRIPTION
**Pull request by Purple-Towel**
updates every instance of "create:brass" to "forge:ingots/brass", should solve #15

### CODE REVIEW

**Comment by Jarva** [comment]
This isn't updating the datagen, so would get overwritten next datagen run, additionally it doesn't use the correct format for tags

**Comment by Purple-Towel** [comment]
Ah, fair enough. Like I said, I'm new to modern Forge, I figured something was up with the recipes being put under the /generated/ directory. Not familiar with how datagen works but I am curious where I could improve on the tags, I noticed some other repos use "#forge:". was that what I was missing?

**Review by zeroregard — APPROVED** [review]
Looks great, thank you very much!

**Comment by zeroregard** [comment]
I can have a look at the data gen part

**Comment by Purple-Towel** [comment]
Alright. Just a small addition, but as Jarva said the tags are wrong. I forgot to change the "item" on each line with "tag".

**Pull request closed without merging**
