### PR TITLE
fix: bring back arcane shaft without the partial model registration crashes

### PR DESCRIPTION
**Pull request by Sethrow2**
The arcane shaft is back, and it also works with ModernFix's dynamic resources. If there are any issues, just let me know!

### CODE REVIEW

**Comment by zeroregard** [comment]
Wow, amazing, that's really appreciated! I'm not a java expert at all, is the fix mostly the `final` keyword or is it something to do with the loading/execution order? I couldn't wrap my head around why exactly it was happening with modernfix.

**Comment by Sethrow2** [comment]
I'm pretty sure it has to do with when the parial model is loaded that fixed it, I mostly just referenced how other Create addons dealt with partial models as they don't seem to crash when dynamic resources in enabled.

**Comment by Sethrow2** [comment]
Hey, I have tried multiple times over the last few days to use the link and while it opens a discord page with "Ars Technica" named, it doesn't actually join me to a server and just has me sitting around indefinitely, I have tried both through the app and in browser. Can you send me a new invite link? Sorry for the trouble!

**Comment by zeroregard** [comment]
Oh dang! Try this one? https://discord.com/invite/pB8JZ4DUAX
This is just the invite link for the Ars Nouveau discord. Within it, there's a section called `Ars Addon Corner`. They allow addon devs to have their own chats in the channel called `addonchats` so in there I started a chat called Ars Technica:
image

**Pull request merged**
